name: BasePlugin
version: ${project.version}
main: xyz.yarinlevi.baseplugin.BasePlugin
api-version: 1.16
softdepend: [PlaceholderAPI]

commands:
  testmessages:
    permission: op

permissions:
  op:
    default: op
